name: learn_flutter
description: A Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.15.7
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

